import type { Metadata } from "next";
import { Geist, Geist_Mono, Rouge_Script } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/contextapi/contextAPI";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const rouge_Script= Rouge_Script ({
  variable:"--font-cursive",
  subsets:["latin"],
  weight:"400",
  display:"swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rouge_Script .variable} antialiased`}
      >
      <ContextProvider>
       {children}
      </ContextProvider>
      </body>
    </html>
  );
}
